version: "3.9"

services:
  indoor_app:
    build:
      context: ./indoor_app
      dockerfile: Dockerfile
    image: "indoor_app:latest"
    container_name: indoor_app
    ports:
      - "5000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb2:27017/indoor_app
    depends_on:
      - mongodb2
      - geoserver
    networks:
      - indoor_network

  mongodb2:
    image: mongo
    container_name: mongodb2
    volumes:
      - ./mongodb-data:/data/db # Bind the volume to a folder in your project
    ports:
      - "27019:27017"
    networks:
      - indoor_network
  geoserver:
    build:
      context: ./geoserver_custom
      dockerfile: Dockerfile
    image: "geoserver_with_mongo:latest"
    container_name: geoserver
    volumes:
      - ./geoserver-data:/opt/geoserver/data_dir # Bind the volume to a folder in your project
    ports:
      - 20502:8080
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=P@ssw0rd
    # depends_on:
    #   postgis:
    #     condition: service_healthy
    networks:
      - indoor_network
    restart: on-failure

volumes:
  mongodb-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/mongodb-data
      o: bind
  geoserver-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/geoserver-data
      o: bind

networks:
  indoor_network:
    driver: bridge
