version: "3.9"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: "indoor_map:dev"
    container_name: web
    ports:
      - "8080:3000"
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
      - POSTGIS_URL=${POSTGIS_URL}
      - NODE_ENV=development
      - DOCKER_ENV=true
    volumes:
      # 🔄 Mount source code for live reload during development
      - .:/usr/app
      - /usr/app/node_modules # Protect container's node_modules
    depends_on:
      - mongo
      - postgis
    networks:
      - backend_network

  mongo:
    image: mongo:noble
    container_name: mongodb
    restart: on-failure
    # Temporary: Running without replica set and keyfile for initial testing
    # Will add replica set support later using Option A (custom Dockerfile)
    command: ["mongod"]

    volumes:
      - mongodb_data:/data/db # Docker named volume for data persistence
      - ./mongo-init:/docker-entrypoint-initdb.d # Mount init scripts
      # Removed keyfile mount temporarily
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - backend_network
  # postgis-data:
  postgis:
    # Option 1: Use official image (current setup with init scripts)
    image: postgis/postgis:16-3.5
    # Option 2: Use custom Dockerfile (uncomment next 2 lines and comment image above)
    # build:
    #   dockerfile: Dockerfile.postgis
    container_name: postgis
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Automatically install PostGIS extensions
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_topology,postgis_raster,fuzzystrmatch
    ports:
      - "5432:5432" # Only accessible from host
    volumes:
      - postgis_data:/var/lib/postgresql/data # Docker named volume for data persistence
      - ./postgis-init:/docker-entrypoint-initdb.d # Mount init scripts
    networks:
      - backend_network

volumes:
  mongodb_data:
    driver: local
  postgis_data:
    driver: local

networks:
  backend_network:
    driver: bridge
