version: "3.9"

services:
  web:
    build: ./
    image: "indoor_app:latest"
    container_name: web
    ports:
      - "80:3000"
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
      - POSTGIS_URL=${POSTGIS_URL}
    depends_on:
      - mongo

    networks:
      - backend_network
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend_network

volumes:
  mongo-data:
  # postgis-data:

networks:
  backend_network:
    driver: bridge
