version: "3.9"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: "indoor_app:dev"
    container_name: web
    ports:
      - "80:3000"
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
      - POSTGIS_URL=${POSTGIS_URL}
      - NODE_ENV=development
      - DOCKER_ENV=true
    volumes:
      # 🔄 Mount source code for live reload during development
      - .:/usr/app
      - /usr/app/node_modules # Protect container's node_modules
    depends_on:
      - mongo
      - postgis
    networks:
      - backend_network

  mongo:
    image: mongo:noble
    container_name: mongodb
    restart: on-failure
    # need to generate keyfile and mount it for replica set authentication
    #(openssl rand -base64 756 > mongo-keyfile
    # chmod 400 mongo-keyfile)
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/data/keyfile"]

    volumes:
      - ./mongodb-data:/data/db # Bind the volume to a folder in your project
      - ./mongo-init:/docker-entrypoint-initdb.d # Mount init scripts
      - ./mongo-keyfile:/data/keyfile:ro
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - backend_network
  # postgis-data:
  postgis:
    # Option 1: Use official image (current setup with init scripts)
    image: postgis/postgis:16-3.5
    # Option 2: Use custom Dockerfile (uncomment next 2 lines and comment image above)
    # build:
    #   dockerfile: Dockerfile.postgis
    container_name: postgis
    platform: linux/amd64
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Automatically install PostGIS extensions
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_topology,postgis_raster,fuzzystrmatch
    ports:
      - "5432:5432" # Only accessible from host
    volumes:
      - ./postgis-data:/var/lib/postgresql/data
      - ./postgis-init:/docker-entrypoint-initdb.d # Mount init scripts
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
