version: "3.9"

services:
  web:
    build: ./
    image: "indoor_app:latest"
    container_name: web
    ports:
      - "80:3000"
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
      - POSTGIS_URL=${POSTGIS_URL}
    depends_on:
      - mongo
      - postgis
    networks:
      - backend_network

  mongo:
    image: mongo:noble
    container_name: mongodb
    restart: on-failure
    volumes:
      - ./mongodb-data:/data/db # Bind the volume to a folder in your project
      - ./mongo-init:/docker-entrypoint-initdb.d # Mount init scripts
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27018:27017"
    networks:
      - backend_network
  # postgis-data:
  postgis:
    image: postgis/postgis:16-master
    container_name: postgis
    platform: linux/amd64
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Only accessible from host
    volumes:
      - ./postgis-data:/var/lib/postgresql/data
      - ./postgis-init:/docker-entrypoint-initdb.d # Mount init scripts
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
